### ISSUE TITLE
Custom Self Service Name not detected

### ISSUE THREAD

**Issue by nlecchi** [txhaflaire/JamfCheck#1]
If the application name is customized Self Servicenon is not detected.
The name of the Self Service application can be customized, such as "Corporate Self Service". In this case JamfCheck cannot find that Self Service is installed.
![Screenshot 2023-09-01 at 09 16 05](https://github.com/txhaflaire/JamfCheck/assets/82441389/acb5235a-73d3-4488-84e5-5544d6d92ea3)

**Comment by txhaflaire** [comment]
@nlecchi Great catch! I've had this on my list for next release, we can fix this by reading `com.jamfsoftware.selfservice.mac` and then the specific array com.jamfsoftware.selfservice.brandinginfo with key appName.

Once i've added this into the new version i will link it to this comment :)

**Comment by txhaflaire** [comment]
@nlecchi No i've found a better way, instead of App Bundles does exists on it's name i'm going to change it for all App Exists checks to check if the App Exists by using it's BundleIdentifier, this will be more robust as names can be changed by end-user for an App but the BundleIdentifier not.

I've got the code in place, expect to be added in v1.1

**Comment by txhaflaire** [comment]
Resolved in release v1.1
